I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 267, in script
    add "fade.png"
Exception: Sayer 'add' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 267, in script
    add "fade.png"
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Cynthia\Descargas\programas\RENPY\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'add' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
test01 1.0
Wed May 29 05:53:36 2024
